//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Semya16
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контроллер.
    /// </summary>
    // *** Start programmer edit section *** (Контроллер CustomAttributes)

    // *** End programmer edit section *** (Контроллер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтроллерE", new string[] {
            "Номер as \'Номер\'",
            "Состояние as \'Состояние\'",
            "ТемпаУстан",
            "ТемпаУстан.Температура"})]
    [AssociatedDetailViewAttribute("КонтроллерE", "Датчик", "ДатчикE", true, "", "Датчик", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("КонтроллерE", "Реле", "РелеE", true, "", "Реле", true, new string[] {
            ""})]
    [View("КонтроллерL", new string[] {
            "Номер as \'Номер\'",
            "Состояние as \'Состояние\'",
            "ТемпаУстан",
            "ТемпаУстан.Температура"})]
    [AssociatedDetailViewAttribute("КонтроллерL", "Датчик", "ДатчикL", true, "", "", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("КонтроллерL", "Реле", "РелеL", true, "", "", true, new string[] {
            ""})]
    public class Контроллер : ICSSoft.STORMNET.DataObject
    {
        
        private bool fСостояние;
        
        private int fНомер;
        
        private IIS.Semya16.ТемпаУстан fТемпаУстан;
        
        private IIS.Semya16.DetailArrayOfДатчик fДатчик;
        
        private IIS.Semya16.DetailArrayOfРеле fРеле;
        
        // *** Start programmer edit section *** (Контроллер CustomMembers)

        // *** End programmer edit section *** (Контроллер CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Контроллер.Номер CustomAttributes)

        // *** End programmer edit section *** (Контроллер.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Контроллер.Номер Get start)

                // *** End programmer edit section *** (Контроллер.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Контроллер.Номер Get end)

                // *** End programmer edit section *** (Контроллер.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроллер.Номер Set start)

                // *** End programmer edit section *** (Контроллер.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Контроллер.Номер Set end)

                // *** End programmer edit section *** (Контроллер.Номер Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Контроллер.Состояние CustomAttributes)

        // *** End programmer edit section *** (Контроллер.Состояние CustomAttributes)
        public virtual bool Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Контроллер.Состояние Get start)

                // *** End programmer edit section *** (Контроллер.Состояние Get start)
                bool result = this.fСостояние;
                // *** Start programmer edit section *** (Контроллер.Состояние Get end)

                // *** End programmer edit section *** (Контроллер.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроллер.Состояние Set start)

                // *** End programmer edit section *** (Контроллер.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Контроллер.Состояние Set end)

                // *** End programmer edit section *** (Контроллер.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Контроллер.
        /// </summary>
        // *** Start programmer edit section *** (Контроллер.ТемпаУстан CustomAttributes)

        // *** End programmer edit section *** (Контроллер.ТемпаУстан CustomAttributes)
        [PropertyStorage(new string[] {
                "ТемпаУстан"})]
        [NotNull()]
        public virtual IIS.Semya16.ТемпаУстан ТемпаУстан
        {
            get
            {
                // *** Start programmer edit section *** (Контроллер.ТемпаУстан Get start)

                // *** End programmer edit section *** (Контроллер.ТемпаУстан Get start)
                IIS.Semya16.ТемпаУстан result = this.fТемпаУстан;
                // *** Start programmer edit section *** (Контроллер.ТемпаУстан Get end)

                // *** End programmer edit section *** (Контроллер.ТемпаУстан Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроллер.ТемпаУстан Set start)

                // *** End programmer edit section *** (Контроллер.ТемпаУстан Set start)
                this.fТемпаУстан = value;
                // *** Start programmer edit section *** (Контроллер.ТемпаУстан Set end)

                // *** End programmer edit section *** (Контроллер.ТемпаУстан Set end)
            }
        }
        
        /// <summary>
        /// Контроллер.
        /// </summary>
        // *** Start programmer edit section *** (Контроллер.Датчик CustomAttributes)

        // *** End programmer edit section *** (Контроллер.Датчик CustomAttributes)
        public virtual IIS.Semya16.DetailArrayOfДатчик Датчик
        {
            get
            {
                // *** Start programmer edit section *** (Контроллер.Датчик Get start)

                // *** End programmer edit section *** (Контроллер.Датчик Get start)
                if ((this.fДатчик == null))
                {
                    this.fДатчик = new IIS.Semya16.DetailArrayOfДатчик(this);
                }
                IIS.Semya16.DetailArrayOfДатчик result = this.fДатчик;
                // *** Start programmer edit section *** (Контроллер.Датчик Get end)

                // *** End programmer edit section *** (Контроллер.Датчик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроллер.Датчик Set start)

                // *** End programmer edit section *** (Контроллер.Датчик Set start)
                this.fДатчик = value;
                // *** Start programmer edit section *** (Контроллер.Датчик Set end)

                // *** End programmer edit section *** (Контроллер.Датчик Set end)
            }
        }
        
        /// <summary>
        /// Контроллер.
        /// </summary>
        // *** Start programmer edit section *** (Контроллер.Реле CustomAttributes)

        // *** End programmer edit section *** (Контроллер.Реле CustomAttributes)
        public virtual IIS.Semya16.DetailArrayOfРеле Реле
        {
            get
            {
                // *** Start programmer edit section *** (Контроллер.Реле Get start)

                // *** End programmer edit section *** (Контроллер.Реле Get start)
                if ((this.fРеле == null))
                {
                    this.fРеле = new IIS.Semya16.DetailArrayOfРеле(this);
                }
                IIS.Semya16.DetailArrayOfРеле result = this.fРеле;
                // *** Start programmer edit section *** (Контроллер.Реле Get end)

                // *** End programmer edit section *** (Контроллер.Реле Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контроллер.Реле Set start)

                // *** End programmer edit section *** (Контроллер.Реле Set start)
                this.fРеле = value;
                // *** Start programmer edit section *** (Контроллер.Реле Set end)

                // *** End programmer edit section *** (Контроллер.Реле Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтроллерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтроллерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтроллерE", typeof(IIS.Semya16.Контроллер));
                }
            }
            
            /// <summary>
            /// "КонтроллерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтроллерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтроллерL", typeof(IIS.Semya16.Контроллер));
                }
            }
        }
    }
}
